-record(stats, {speed=null::integer(), might=null::integer(), sanity=null::integer(), knowledge=null::integer()}).
-type stats()::#stats{}.
-type color()::purple | green | white | blue | red | orange.
-type variant()::front | back.
-record(character, {color=null::color(), variant=null::variant(), stats=null::stats()}).
-type character()::#character{}.
-type playerid()::binary().
-type gameid()::binary().
-record(player, {gameid=null::gameid(), playerid=null::playerid(), name=null::string(), character=null::character()}).
-type player()::#player{}.
-record(playerrec, {id=null::binary(), player=null::player()}).
-record(gamerec, {gameid=null::gameid(), players=null::[player()]}).
