application: betrayal-house
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /components/
  static_dir: bower_components/

- url: /images/
  static_dir: images/

- url: /
  static_files: index.html
  upload: index.html
