application: betrayal-house
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /components/
  static_dir: bower_components/

- url: /images/
  static_dir: images/

- url: /icons/
  static_dir: icons/

- url: /manifest.json
  static_files: manifest.json
  upload: manifest.json

- url: /
  static_files: index.html
  upload: index.html

- url: /.well-known/.*
  script: acme.app
